fix: logging import in conftest
Because I was getting this error in my peer selection tests:
```python
    @pytest.fixture(autouse=True)
    def enable_tplr_logger_propagation():
>       tplr.logging.logger.setLevel("INFO")
E       AttributeError: module 'logging' has no attribute 'logger'
```